# Generated by Django 6.0.4 on 2026-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
